apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: vand1992/simple_blog_api
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USERNAME
              value: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_DB
              value: simple_blog_api
            - name: POSTGRES_PORT
              value: "5432"
